### PR TITLE
Made new migrations to fix migration conflict

### PR DESCRIPTION
**Pull request by poeticabdul**

### CODE REVIEW

**Comment by BorderITS** [comment]
migration conflict is happening after I pulled in the new request

**Comment by poeticabdul** [comment]
Really sorry about that. This is going to cost some time. Can you delete the db and the migration files that are not same as the recent push from me?

@lcabrini do you have experience with open source way of handling this kind of conflicts?

**Comment by BorderITS** [comment]
ok

**Comment by BorderITS** [comment]
(ENV) nelson@Nelson-Zorin-OS9:~/Projects/amadaa$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/nelson/Projects/amadaa/amadaa/urls.py", line 29, in <module>
    url('^sales/', include('sales.urls')),
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/nelson/Projects/amadaa/sales/urls.py", line 2, in <module>
    from sales.views import manage_payment_terms
  File "/home/nelson/Projects/amadaa/sales/views.py", line 12, in <module>
    from .forms import SalesOrderEditForm
  File "/home/nelson/Projects/amadaa/sales/forms.py", line 47
    print "-------------"
                        ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by poeticabdul** [comment]
But after doing this, you'll have to recreate all the data. New superuser etc.

**Comment by BorderITS** [comment]
this is what I get after I deleted the db and I tried to do a new migration

**Comment by poeticabdul** [comment]
hmmm, did you remove the migration files in the migration folders of sales, contact and product that are no more being used.

**Comment by poeticabdul** [comment]
if this will cause a problem, can you start the project afresh, I am sorry for giving you guys some work

**Comment by BorderITS** [comment]
no problem

**Comment by poeticabdul** [comment]
wait a minute, please let me make a pull request, then you can go ahead to try again and if it doesn't work, you start afresh

**Comment by BorderITS** [comment]
okay but its too late

**Comment by BorderITS** [comment]
am sorry

**Comment by poeticabdul** [comment]
no problem

**Comment by BorderITS** [comment]
ok

**Pull request merged**
