### PR TITLE
Manage Product Categories

### PR DESCRIPTION
**Pull request by lcabrini**

### CODE REVIEW

**Comment by BorderITS** [comment]
Application not installed properly

**Comment by BorderITS** [comment]
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fd52b882400>
Traceback (most recent call last):
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/nelson/Projects/amadaa/amadaa/urls.py", line 25, in <module>
    url('^product/', include('product.urls'))
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/nelson/Projects/amadaa/product/urls.py", line 2, in <module>
    from product.views import ProductCategoryList, ProductCategoryDetail, ProductCategoryCreate, ProductCategoryUpdate, ProductCategoryDelete
  File "/home/nelson/Projects/amadaa/product/views.py", line 5, in <module>
    from product.models import ProductCategory
  File "/home/nelson/Projects/amadaa/product/models.py", line 7, in <module>
    class ProductCategory(AmadaaModel):
  File "/home/nelson/Projects/amadaa/ENV/lib/python3.4/site-packages/django/db/models/base.py", line 113, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class product.models.ProductCategory doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by lcabrini** [comment]
Yes, because you removed it didn't you? Put product back in settings.py

**Comment by BorderITS** [comment]
Manage Product Categories #120 gives error and i can't login again

**Comment by lcabrini** [comment]
It works fine here. Did you go and re-add the product app in the INSTALLED_APPS list? Remember that you removed it before. If you study the above error, it indicates that this is the case. However, I still think we should open bug issues when these things happen. It is a (possible) bug, and needs to be treated as such.

**Comment by BorderITS** [comment]
ok

**Comment by BorderITS** [comment]
it's working now

**Comment by lcabrini** [comment]
File a bug.

**Pull request merged**
