### PR TITLE
Fixed footer

### PR DESCRIPTION
**Pull request by SirMac**

### CODE REVIEW

**Comment by BorderITS** [comment]
well done @SirMac

**Comment by SirMac** [comment]
I ll like replace the "plus" signs in the Product page with an image. Or is there any specific reason for adding to the product page?
product page

**Comment by lcabrini** [comment]
The reason for the plus sign is that it is a bootstrap default icon. I don't mind an image, but if we are going to do that there are two things to keep in mind.

1. the images should be consistent. It doesn't look good if we have some colorful images with a pseudo-3D look, and others that are flat and monochrome.
2. we need to mindful of the sources of any images we use and understand their terms clearly. We are an open-source public project, and we wouldn't want to get into copyright issues.

**Comment by SirMac** [comment]
Sure

**Pull request merged**
